// <auto-generated />
namespace AMS_BE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetUserfieldstringlimitsanddefaultvaluesforbooleansanddates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetUserfieldstringlimitsanddefaultvaluesforbooleansanddates));
        
        string IMigrationMetadata.Id
        {
            get { return "201710251440256_Set User field string limits and default values for booleans and dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
