// <auto-generated />
namespace AMS_BE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TriedandrolledbackFKinbothUserandLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TriedandrolledbackFKinbothUserandLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201710251729187_Tried and rolled-back FK in both User and Location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
